spring:
  application:
    name: ReCharger GCP
  cloud:
    gcp:
      logging:
        enabled: true
  datasource:
    url: "<JDBC_LINK_SEE_README>"
    username: "<SPECIFY_IF_NOT_ROOT>"
    password: "<USER_PASS_IF_CONFIGURED>"
