spring:
  application:
    name: ReCharger Spring Default Profile
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/data}"
    username: root
    password: "${SPRING_DATASOURCE_PASSWORD:password}"
  flyway:
    out-of-order: true
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "<GOOGLE_CLIENT_ID>"
            client-secret: "<GOOGLE_CLIENT_SECRET>"
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: "accounts.google.com"
          jwk-set-uri: "https://www.googleapis.com/oauth2/v3/certs"
# to allow swagger-ui to perform requests against HTTPS
server:
  forward-headers-strategy: framework
