spring:
  application:
    name: ReCharger Spring Default Profile
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/data}"
    username: root
    password: "${SPRING_DATASOURCE_PASSWORD:password}"
  flyway:
    out-of-order: true
  jpa:
    hibernate:
      ddl-auto: validate
