version: '3'

services:

  test-recharge-database:
    image: mysql:8.1.0
    container_name: test-recharge-database
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: 'data'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
